### ISSUE TITLE
Irreführender Name

### ISSUE THREAD

**Issue by L3P3** [LFF5644/virtualDisk#1]
Habe mir das jetzt genauer angesehen.

Schön, was du so lernst, aber das ist genau so wenig eine Festplatte, wie mein Seng2 damals ein Betriebssystem war!

Hochstapler! :stuck_out_tongue:

**Comment by LFF5644** [comment]
was ist "Seng2" ? habe auf [google](https://www.google.com/search?q=Seng2) nichts passendes gefunden?
https://www.google.com/search?q=Seng2

**Comment by LFF5644** [comment]
der name ist passend

**Comment by L3P3** [comment]
Nein, das ist keine DISK!

**Comment by LFF5644** [comment]
doch mit ein paar tricks kann man sie auf eine cd schreiben xD

in der tehorie wenn man im programm "/dev/sr0" als datei nimt und eine wiederbeschreibbare dvd einlegt und dann das programm "a" als sudo laufen läst "b" wenn mann "sudo chmod 777 /dev/sr0" eingibt habben alle nutzer rechte auf diese datei
